[project]
name = "deepfinnk-bunq-agent"
version = "0.1.0"
description = "A Flask-based Multi-Agent Collaboration Platform (MCP) server designed to interact with the Bunq API using the CAMEL AI framework."
authors = [
    { name = "Victor Hornet" },
    { name = "Andrea Onofrei" },
    { name = "Yulin Chen" },
    { name = "Denis Krylov" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bunq-sdk>=1.14.18",
    "camel-ai[owl]>=0.2.50",
    "docx2markdown>=0.1.1",
    "flasgger>=0.9.7.1",
    "flask[async]>=3.1.0",
    "mcp[cli]>=1.6.0",
    "xmltodict>=0.14.2",
]
